steps:
  # Step 1: Build with Maven
  - name: 'maven:3.8.4'
    args: ['mvn', 'clean', 'install']

  # Step 2: Build the Docker Image
  - name: gcr.io/cloud-builders/docker
    args: [
      'build', 
      '-t', 
      'gcr.io/shaped-infusion-402417/docker-spring-boot-java-web:latest',
      '.'
    ]

  # Step 3: Push the Docker Image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/shaped-infusion-402417/docker-spring-boot-java-web:latest']

  # Step 4: Install jq
  - name: 'ubuntu'
    entrypoint: 'apt-get'
    args: ['update', '-y']
  - name: 'ubuntu'
    entrypoint: 'apt-get'
    args: ['install', '-y', 'jq']

  # Step 5: Scan the container image with AccuKnox and save the report
  - name: 'accuknox/accuknox-container-scan'
    args: [
      'image', 
      '--format', 'json', 
      '--output', '/workspace/accuknox-report.json', 
      '${_IMAGE_URL}:${_IMAGE_TAG}',
      '--exit-code', '1',
      '--severity', 'HIGH,CRITICAL'
    ]
    id: 'accuknox-container-scan'

  # Step 6: Upload the AccuKnox report to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/accuknox-report.json', 'gs://aditya-cicd-test/accuknox-report.json']
    waitFor: ['accuknox-container-scan']

  # Step 7: Print the AccuKnox container scan results
  - name: 'ubuntu'
    entrypoint: 'cat'
    args: ['/workspace/accuknox-report.json']
    waitFor: ['accuknox-container-scan']

  # Step 8: Exit if Critical or High Vulnerabilities are Found
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'jq ".vulnerabilities | if length == 0 then exit 0 else exit 1 end" /workspace/accuknox-report.json'
      ]
    waitFor: ['accuknox-container-scan']

  # Step 9: Apply Kubernetes Configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-gcb-security-bu'
    waitFor: ['accuknox-container-scan']

  # Step 10: Update the Deployment Image
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 
      'image', 
      'deployment', 
      'spring-boot-java-web', 
      'spring-boot-java-web=gcr.io/shaped-infusion-402417/docker-spring-boot-java-web:latest'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-gcb-security-bu'
    waitFor: ['accuknox-container-scan']

# Push the image to Google Container Registry with the latest tag
images: [
   'gcr.io/shaped-infusion-402417/docker-spring-boot-java-web:latest'
]

# Specify the logs bucket and build timeout
logsBucket: 'gs://aditya-cicd-test'
timeout: '1200s'

# Define substitutions
substitutions:
  _IMAGE_URL: 'gcr.io/shaped-infusion-402417/docker-spring-boot-java-web'
  _IMAGE_TAG: 'latest'
  _CSPM_URL: 'cspm.demo.accuknox.com'
  _TENANT_ID: '167'
