steps:
# Step 1
#Step 1: Build with Maven
- name: 'maven:3.8.4'
  args: ['mvn', 'clean', 'install']
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/docker-spring-boot-java-web:latest',
   '.'
  ]
# Step 2
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/docker-spring-boot-java-web:latest']
# Step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-gcb-security-bu'
# Step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   '', 
   'spring-boot-java-web=gcr.io/$PROJECT_ID/docker-spring-boot-java-web:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-gcb-security-bu'
  # Push the image to Google Container Registry with the latest tag
images: [
   'gcr.io/$PROJECT_ID/docker-spring-boot-java-web:latest'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
